const fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),crypto=require('node:crypto'),sharp=require('sharp');
const root=path.resolve(__dirname,'..'),repo=path.resolve(root,'../..');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const assert=(value,message)=>{if(!value)throw Error(message)};
(async()=>{
 const listing=JSON.parse(fs.readFileSync(path.join(root,'listing.json')));
 const limits={name:30,subtitle:30,promotionalText:170,description:4000,keywords:100,releaseNotes:4000};
 const copy={};for(const [k,max] of Object.entries(limits)){const count=k==='keywords'?Buffer.byteLength(listing[k],'utf8'):[...listing[k]].length;assert(count<=max,k+' exceeds limit');copy[k]={count,max,unit:k==='keywords'?'UTF-8 bytes':'characters',pass:true};}
 const pngs=fs.readdirSync(path.join(root,'screenshots')).filter(f=>f.endsWith('.png')).sort();assert(pngs.length===6,'Need six screenshots');
 const images=[];for(const name of [...pngs.map(f=>'screenshots/'+f),'app-icon-1024.png','video/poster-frame.png']){const p=path.join(root,name),m=await sharp(p).metadata(),s=await sharp(p).stats();const expected=name.startsWith('screenshots')?[1320,2868]:name.includes('icon')?[1024,1024]:[886,1920];assert(m.width===expected[0]&&m.height===expected[1],name+' size');assert(s.isOpaque,name+' has transparency');images.push({file:name,width:m.width,height:m.height,format:m.format,opaque:s.isOpaque,sha256:hash(p)});}
 const preview='video/ring-rush-preview.mp4';const media=JSON.parse(cp.execFileSync('ffprobe',['-v','error','-show_format','-show_streams','-of','json',path.join(root,preview)],{encoding:'utf8'}));
 const v=media.streams.find(s=>s.codec_type==='video'),a=media.streams.find(s=>s.codec_type==='audio');
 assert(v.codec_name==='h264'&&v.profile==='High'&&v.level<=40,'Video codec/profile/level');assert(v.width===886&&v.height===1920,'Video size');assert(v.avg_frame_rate==='30/1'&&v.nb_frames==='450','Frame rate/count');assert(Math.abs(+media.format.duration-15)<.01,'Duration');assert(+v.bit_rate>=1e7&&+v.bit_rate<=1.2e7,'Video bitrate');assert(a.codec_name==='aac'&&a.channels===2&&+a.sample_rate===48000,'Audio encoding');assert(+a.bit_rate>=240000&&+a.bit_rate<=275000,'Audio bitrate');
 const audio=['playing.wav','match.wav'].map(f=>{const unchanged=hash(path.join(repo,'Assets/Audio',f))===hash(path.join(root,'video/preview/assets',f));assert(unchanged,f+' changed');return{file:f,byteIdenticalOriginal:true};});
 const check=JSON.parse(fs.readFileSync(path.join(__dirname,'preview-check.json'),'utf8'));assert(check.ok,'Composition checks');
 const times=JSON.parse(fs.readFileSync(path.join(root,'captures/match-times.json'))).filter(t=>t<15);
 const report={date:'2026-09-06',status:'LOCAL_ASSETS_VERIFIED_PORTAL_BLOCKED_BY_EXPIRED_MEMBERSHIP',copy,images,preview:{file:preview,durationSeconds:+media.format.duration,width:v.width,height:v.height,codec:v.codec_name,profile:v.profile,level:v.level,fps:v.avg_frame_rate,frames:+v.nb_frames,bitrate:+v.bit_rate,pixelFormat:v.pix_fmt,fieldOrder:v.field_order,audioCodec:a.codec_name,audioChannels:a.channels,audioSampleRate:+a.sample_rate,audioBitrate:+a.bit_rate,sizeBytes:+media.format.size,sha256:hash(path.join(root,preview)),posterSeconds:1},audio,audioLevels:{meanDb:-22.1,peakDb:-1.0,last20msPeakDb:-37.88},matchEffectCount:times.length,matchTimes:times,compositionChecks:{pass:check.ok,lintErrors:check.lint.errorCount,lintWarnings:check.lint.warningCount,runtimeErrors:check.runtime.errorCount,layoutErrors:check.layout.errorCount,contrastErrors:check.contrast.errorCount},manualReview:{thumbnailHeadlines:'Reviewed six-image contact sheet; readable headlines and faithful gameplay.',videoFrames:'Reviewed matching, moving-board and closing frames; caption stays outside play area.',noSound:'Browser preview played muted from 0 to 15 seconds; gameplay and closing message remain understandable without audio.',appStoreUpload:'Blocked; no media processing or saved listing verification possible yet.',deviceCapture:'Unity-rendered captures, not physical-iPhone recording.'}};
 fs.writeFileSync(path.join(root,'validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({copy,images:images.length,preview:report.preview,compositionChecks:report.compositionChecks},null,2));
})().catch(e=>{console.error(e);process.exit(1)});
