import { defineApp } from "convex/server";
import aggregate from "@convex-dev/aggregate/convex.config";
import workflow from "@convex-dev/workflow/convex.config";
import rateLimiter from "@convex-dev/rate-limiter/convex.config";
const app = defineApp();
app.use(aggregate, { name: "dailyScores" });
app.use(aggregate, { name: "leaderboardScores" });
app.use(aggregate, { name: "leaderboardAllTimeScores" });
app.use(workflow);
app.use(rateLimiter);
export default app;
